Add timeout to rabbitmqctl wait statement
rabbitmq/rabbitmq-server-release pull request #129
Opened 2020-04-13 20:45 UTC by nicolasbock

After starting the RabbitMQ server process, the startup script will
wait for the server to start by calling `rabbitmqctl wait` and will
time out after 10 s.

The startup time of the server depends on how quickly the Mnesia
database becomes available and the server will time out after
`mnesia_table_loading_retry_timeout` ms times
`mnesia_table_loading_retry_limit` retries. By default this wait is
30,000 ms times 10 retries, i.e. 300 s.

The mismatch between these two timeout values might lead to the
startup script failing prematurely while the server is still waiting
for the Mnesia tables.

This change introduces a variable and the `--timeout` option into the
startup script so that the two timeout values are identical.

Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

2020-04-13 20:45 UTC, pivotal-issuemaster commented
@nicolasbock Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-server-release&pullRequestId=129)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-server-release&pullRequestId=129) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-04-13 21:35 UTC, michaelklishin commented
If a node has to rebuild indices or has a large amount of disk resident data it can take longer than 30 seconds to start. If it's a [node restart](https://www.rabbitmq.com/clustering.html#restarting) and peers are taking longer to start, it will take longer than 30 seconds to start.

Boot timeouts is a great idea in theory and are really easy to get wrong in practice.

However, [`rabbitmqctl wait` timeout](https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/commands/wait_command.ex#L51) only waits for a pid file to be dropped, not complete node boot, unlike `rabbitmqctl await_node_startup`. In `3.8.4` this will happen at [prelaunch stage](https://github.com/rabbitmq/rabbitmq-server/blob/278a1fedfb569b8b6b1dd56a44f0a01fa3500a43/apps/rabbitmq_prelaunch/src/rabbit_prelaunch.erl#L113) so it won't wait for data recovery or schema sync from peers so that should fit into 30 seconds in most cases.

@dumbbell do you remember how it worked before the introduction of prelaunch?

@dumbbell @gerhard @lukebakken thoughts on this idea and the proposed default?

2020-04-13 21:42 UTC, nicolasbock commented
Would you suggest to use `await_node_startup` instead?

In the systemd service file the service timeout is set to 3600 seconds which is considerably longer than the timeout used in the SysV init script. Would you favor to bring the two startup mechanisms onto equal footing?

2020-04-14 11:20 UTC, dumbbell commented
`rabbitmqctl wait` waits for `rabbit:is_running()` to return true. It means all core+plugins boot steps were executed and all enabled plugins are started. After the introduction of rabbitmq_prelaunch and the redesign of `rabbit:start/2`, it means it waits for slightly longer compared to before, but I don't remember the exact details.

I believe `rabbitmqctl wait` does the right thing. The two problematic situations are if RabbitMQ fails to start:
* before the PID file is written
* before Erlang distribution is enabled

... in which case the command will waste its time waiting for a node which will never appear.

Perhaps the proper solution would be to defer things like indices rebuild to after the time we mark RabbitMQ as ready.

2020-04-14 21:06 UTC, nicolasbock commented
Thanks for the comments @dumbbell . Regarding a failure _before_ the PID file is written, we could introduce a second timeout to wait for the PID file. This would complicate the logic of the `start_rabbitmq()` function though.

Regarding the enablement of the Erlang distribution, I don't think I quite understand what you mean. Could you elaborate?

2020-04-15 09:59 UTC, dumbbell commented
Erlang distribution is the way Erlang nodes communicate between each other. RabbitMQ uses this for clusters but also for the communication between the RabbitMQ node and the CLI.

When a RabbitMQ node starts, there is no Erlang distribution enabled because it does several checks before turning it on, in order to show human friendly errors if it can't. Enabling distribution means that the RabbitMQ node gets a name (`rabbit@$(hostname -s)` by default basically), registers itself in the local epmd daemon and listens on a TCP port for communication with other RabbitMQ nodes and the CLI.

After the PID file appears, `rabbitmqctl wait` tries to contact the RabbitMQ using this Erlang distribution mechanism, in order to run a function on the remote node (remote from the CLI's point of view) to determine if RabbitMQ is ready.

2020-04-16 12:37 UTC, dumbbell commented
To come back to your patch, perhaps the wait timeout should be bumped to one hour, like the systemd script. If services are started in parallel (I don't know if that's always the case), then it doesn't really matter how long the SysV init script takes.

I'm not aware of anyone complaining about the wait timeout with systemd so far.

What do you think @michaelklishin?

2020-04-16 13:51 UTC, michaelklishin commented
I'm not aware of any cases or mailing list discussions where the systemd timeout would need changing. 1 hour is a fairly long period of time. 30 seconds is way too short and risky. I'd use a value of 10 minutes as a compromise, although going with the systemd unit default also makes sense. If we were to change this timeout it would make sense to update to both.

2020-04-16 14:45 UTC, nicolasbock commented
Thanks for the feedback @dumbbell and @michaelklishin ! I'll update the PR to sync both init scripts to 10 minutes.

2020-04-16 15:02 UTC, michaelklishin commented
@nicolasbock thank you. @dumbbell is the proposed new default of 10 minutes fine with you?

2020-04-17 08:09 UTC, dumbbell commented
Yes, that's fine.

2020-04-17 08:10 UTC, dumbbell requested changes
Could you please make the same change in the RPM package? To keep them in sync.

2020-04-17 12:22 UTC, nicolasbock commented
Done @dumbbell

2020-04-17 17:40 UTC, michaelklishin approved these changes

2020-04-17 17:41 UTC, merged

2020-04-17 17:41 UTC, michaelklishin commented
Thank you! We will backport this a bit later.

2020-04-17 17:49 UTC, nicolasbock commented
Thanks!

2020-04-20 12:39 UTC, dumbbell commented
Thank you @nicolasbock :)

2020-06-10 08:43 UTC, michaelklishin commented
We will backport this for `3.8.5`.