OCF RA: Add new limit_nofile parameter to both OCF resource agents
rabbitmq/rabbitmq-server-release pull request #21
Opened 2017-03-29 20:22 UTC by vuntz

This enables to change the limit of open files, as the default on
distributions is usually too low for rabbitmq. Default is 65535.

The initial change is from @aplanas, but I guess we want a similar change in the other RA.

2017-03-30 07:57 UTC, aplanas approved these changes

2017-03-30 08:23 UTC, binarin requested changes

2017-03-30 08:23 UTC, binarin commented on scripts/rabbitmq-server-ha.ocf
> +OCF_RESKEY_limit_nofile=65535
`_default` is missing

2017-03-30 08:23 UTC, binarin commented on scripts/rabbitmq-server.ocf
> +<content type="string" default="${OCF_RESKEY_limit_nofile}" />
Should it be  `_default`  here to? Otherwise it's inconsistent between 2 scripts.

2017-03-30 08:41 UTC, michaelklishin commented
Please address @binarin's comments.

2017-03-30 14:09 UTC, vuntz commented on scripts/rabbitmq-server-ha.ocf
> +OCF_RESKEY_limit_nofile=65535
Doh, thanks, fixed.

2017-03-30 14:09 UTC, vuntz commented on scripts/rabbitmq-server.ocf
> +<content type="string" default="${OCF_RESKEY_limit_nofile}" />
Fixed.

2017-03-30 15:11 UTC, michaelklishin commented
@binarin may I ask you to take another look? :) Thanks.

2017-03-30 15:41 UTC, binarin commented
Looks good so far. I'm going to test this version of the script in the wild and I'll try to post my results tomorrow.

2017-03-31 16:27 UTC, binarin commented
It shouldn't change the behavior by default - `set_limits` should be called only when the pacemaker parameter is explicitly set. Otherwise it thwarts attempts to manage the limits by external mechanisms.

2017-04-03 09:47 UTC, vuntz commented
> It shouldn't change the behavior by default - set_limits should be called only when the pacemaker parameter is explicitly set. Otherwise it thwarts attempts to manage the limits by external mechanisms.

So would you suggest to have the default value an empty string?

2017-04-03 09:54 UTC, michaelklishin commented
@vuntz @binarin can we change the default to something higher instead? I understand that those who manage OS limits "out of band" would find it very annoying if their settings were overwritten. However, as you definitely know the Linux defaults are absolutely inadequate for any server (1024 file descriptors, seriously?).

So can we find a way to not have the value blank by default *and* let folks such as @binarin to manage OS limits their preferred way?

2017-04-03 10:31 UTC, vuntz commented
> can we change the default to something higher instead?

Such as? Right now, the default is 65535, so do you mean higher than that or higher than 1024?

> So can we find a way to not have the value blank by default and let folks such as @binarin to manage OS limits their preferred way?

I'm not sure this can be done in a reasonable way; the obvious trick that comes to my mind is to check "ulimit -n" for the rabbitmq user, but I'm not sure it'd catch everything that is wanted.

2017-04-03 10:38 UTC, binarin commented
I think that `set_limits`  shouldn't set limit to a value lower than that is currently set. This'll put only the lower limit on what can be set through external mechanisms.

2017-04-04 13:12 UTC, michaelklishin commented
What @binarin is suggesting above might be sufficient. @vuntz WDYT?

2017-04-04 13:39 UTC, vuntz commented
> What @binarin is suggesting above might be sufficient. @vuntz WDYT?

I just pushed something for this; I'm honestly unsure if that's the correct way to implement the idea, though. And I'm also starting to wonder if we really want this in the resource agent.

@aplanas is there reason you didn't simply update rabbitmq-env.conf to call ulimit?

2017-04-04 14:17 UTC, aplanas commented
@vuntz ahh no, I never tried it, but looks like that debian[1] is using this to set the ulimit, but as a second option after systemd.

[1] https://www.rabbitmq.com/install-debian.html

2017-04-04 14:40 UTC, michaelklishin commented
@aplanas it's not a "second option" but rather one of the easiest options on distributions that do not use systemd. On those that do it won't actually have any effect, and recent Debian and Ubuntu releases are systemd-based, so we highlight that the difference.

2017-04-05 08:14 UTC, vuntz commented
After sleeping over it, I think I like the simplicity of having this in the resource agent. In the end, this is similar to what is recommended for systemd with one setting in one location, so I'd like to keep the patch.

2017-04-05 11:38 UTC, michaelklishin commented
@binarin OK with you to merge?

2017-04-05 14:08 UTC, binarin commented
Yes

2017-04-05 14:49 UTC, merged