Use reload-or-restart / restart instead of try-restart
rabbitmq/rabbitmq-server-release pull request #95
Opened 2019-03-06 18:33 UTC by lukebakken

Fixes #94 

@dumbbell I'm not sure if [this line](https://github.com/rabbitmq/rabbitmq-server-release/blob/master/packaging/RPMS/Fedora/rabbitmq-server.spec#L211) should be changed to use `reload-or-restart` as well as I'm not quite sure what is being accomplished there.

2019-03-07 06:35 UTC, michaelklishin commented
Should we use [just restart](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-managing_services_with_systemd-services)? The goal is to ensure a restart, and `reload` seems to be solving a different problem.

2019-03-07 09:15 UTC, dumbbell commented
`try-restart` is being used on purpose, so that the service is not started if it was stopped before the upgrade. There is `reload-or-try-restart`, perhaps we could use that, but we know that RabbitMQ doesn't support a reload, so I don't see how this fixes the problem.

Could it be that the state of the RabbitMQ service is inconsistent and a `try-restart` does not restart it because systemd somehow believes RabbitMQ is stopped?

In particular, I see that we stop RabbitMQ in the `%preun` (preuninstall) phase. I'm not an expert with RPM packaging and I don't know how phases are executed in the case of an upgrade. But it would be logical that `%preun` follows a similar logic to `%postun` and therefore, it should have an argument indicating if it's an upgrade (as opposed to an uninstall).

Now that I wrote this paragraph, it looks like the bug is the `%preun` phase, not the `%postun` one. Let me do some tests.

2019-03-07 17:32 UTC, lukebakken commented
I assumed that `reload` is necessary to have `systemd` reload the unit, but maybe that's not necessary.

> Could it be that the state of the RabbitMQ service is inconsistent and a try-restart does not restart it because systemd somehow believes RabbitMQ is stopped?

`try-restart` won't start a stopped service. Since an upgrade stops the service, it won't be started again. This is what surprises the person who reported this issue in #94.

We can check whether this is an upgrade vs an uninstall by looking at `$1`.

I don't think we should care if RabbitMQ is running before the upgrade or not. When you install RabbitMQ, the expectation is that it is started. The same expectation should apply to an upgrade. If the administrator really doesn't want RabbitMQ started after an upgrade, they can disable the `rabbitmq-server.service` unit prior to the upgrade. I think attempting a restart will fail at this point - I'll give it a test.

2019-03-07 17:54 UTC, michaelklishin commented
My concern is that `reload` won't be effective when there is a running node. So I think a basic `restart` is what we want.

2019-03-07 18:03 UTC, lukebakken commented
This is interesting, [`reload-or-restart`](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units) sends the service (if running) a signal to reload its configuration (which RMQ doesn't support). I'm assuming that the service must respond with an `OK` of some sort. If that doesn't happen, the service is restarted.

So in our case, we should use `restart`.

2019-03-08 08:53 UTC, dumbbell commented
> When you install RabbitMQ, the expectation is that it is started.

That's the expectation on Debian, because this behavior is defined by the Debian Policy. However, this is the opposite on Fedora: it is considered insecure to start a service with default configuration on package install. Personally, I prefer the latter.

In our package testsuites, we verify exactly these behaviors. After install:
* the service is running on Debian
* the service is stopped on RHEL-like

Now, after upgrade, I don't know if there is a defined behavior on either Debian or RHEL. I believe the service should be left in the state it was prior the upgrade.

To me the correct fix would be to record the fact that RabbitMQ was running in one of the hook, stop it, let the upgrade, and restart it after the upgrade. I'm not yet sure which hooks should do the stop+record and the restart.

Here is the sequence of hooks during an upgrade:
1. `%pre` from the new package is executed (with `$1=2`).
2. Files from the new package are installed.
3. `%post` from the new package is executed (with `$1=2`).
4. `%preun` from the old package is executed (with `$1=1`).
5. Files not referenced by the new package are removed.
6. `%postun` from the old package is executed (with `$1=1`).

So far, I'm thinking of:
1. Record the fact that RabbitMQ is running or not in `%pre` (like, `touch /var/lib/rabbitmq/rabbitmq-was- started`).
2. Stop RabbitMQ in `%pre` because old files are replaced by new ones just after that.
3. Start RabbitMQ again in `%postun` if the `%pre` said so.

But I'm not 100% convinced about the solution.

2019-03-08 08:53 UTC, dumbbell requested changes
See my previous comment.

2019-03-08 11:00 UTC, dumbbell commented
I was testing the upgrade scenario with a reinstall of the same package. In this case, the `%preun 1` and `%postun 1` hooks of the package are not executed, only `%pre 2` and `%post 2`. Therefore, I'm going to test the described solution, but with the restart handled in `%post` instead of `%postun`.

2019-03-08 11:22 UTC, dumbbell commented
Ok, the solution fixes the the problem discussed. To sum it up:

1. Record the fact that RabbitMQ is running or not in `%pre` when this is an upgrade (i.e. `$1 = 2`). To do this, we create `/var/lib/rabbitmq/rabbitmq-was-running-before-upgrade` if it's running.
2. Stop RabbitMQ in `%pre` because old files are replaced by new ones just after that. It is already the case today.
3. Start RabbitMQ again in `%post` (again, when this is an upgrade) if `/var/lib/rabbitmq/rabbitmq-was-running-before-upgrade` exists, and remove that file.

What do you think @lukebakken & @michaelklishin?

2019-03-08 13:32 UTC, lukebakken commented
@dumbbell that's great. Feel free to change this branch. I'll be back online in a couple hours.

2019-03-08 14:56 UTC, michaelklishin commented
@dumbbell sounds good. I guess I'll have to research what the Chef cookbook should do (I don't think it messes with the service at the moment, possibly by design).

2019-03-11 11:50 UTC, michaelklishin commented
Closing in favour of a different PR that would [do the following](https://github.com/rabbitmq/rabbitmq-server-release/pull/95#issuecomment-470896212). Per discussion with @dumbbell.

2019-03-11 11:50 UTC, closed without merging

2019-03-11 14:02 UTC, dumbbell commented
Pull request #96 supersedes this one.